interested-parties.md
Follow-up to the comments by @dyladan in https://github.com/openfeatureflags/governance/pull/8 . Indeed we want to have the project friendly to individual contributors
=> Extend the Interested Parties list

README.md, governance-charter.md
Foundation work for #1. The governance document is based on the OpenTelemetry, Keptn and some bits of Contributor Covenant and TAG App Delivery
Preview: https://github.com/openfeatureflags/governance/tree/governance-docs
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>
=> Create a bootstrap governance document

governance-charter.md
As discussed on Slack, adding a proposal for the Technical Steering committee entity
=> Add Technical Steering committee to the charter

community-members.md, governance-charter.md
Signed-off-by: Alois Reitbauer <a.reitbauer@gmail.com>
* Adding Alex to the governance board
* Remove double mention of governance members
* Remove Kevin from governance board
=> Update and clean up governance board structure

community-members.md
Signed-off-by: Alois Reitbauer <a.reitbauer@gmail.com>
=> Adding David as community manager

.github/CODEOWNERS
Signed-off-by: David Hirsch <79513080+DavidPHirsch@users.noreply.github.com>
adding to codeowners for community
=> Update to codeowners

tech-committee-charter.md
With the term of the initial TC coming up soon, as well as recent changes by @DavidPHirsch [here](https://github.com/open-feature/community/pull/155/files), I though it was about time to formalize the responsibilities of the TC.
=> doc: add TC responsibilies and examples

config/open-feature/org.yaml, tools/peribolosbuilder.go
it seems like setting the main branch causes issues with peribolos.
We are getting errors that it can not be set.
=> fix: removing the setting of the main branch

config/open-feature/org.yaml
Move @thschue to emeritus at his request. This still keeps him in the org, which makes him `@-able`.
@aepfli is there anything else to think about here? He is [already removed from CN-matainers](https://github.com/open-feature/community/pull/185).
@thschue please let me know if you don't want this, or if you'd like to be removed from the membership as well. Thanks for all your help and efforts, and best of luck!
=> chore: move thschue to emeritus

README.md
Problem: I couldn't find where to sign up for emails on this page
Solution: I added a Mailing List section to make it easier for folx to join the CNCF mailing list.
- adds a Mailing List section to the Community github page
=> Add Mailing List section to community page

CONTRIBUTOR_LADDER.md
Link was broken for line 84 to preview the current version of the template (missing an "s" in the membership.md name/link), fixed now.
- new link: https://github.com/open-feature/community/issues/new?labels=membership&template=membership.md
=> Fix broken link for checklist to become org member

config/open-feature/org.yaml
Adds [lukas-reining](https://github.com/lukas-reining) to org, who contributed the JS config-cat provider.
=> Add lukas-reining to org

config/open-feature/org/workgroup.yaml
Adds a number of people to org approvers who have well-established roles elsewhere.
Note this group controls the following repos (as defined in this file):
- ofep
- community
- community-tooling
- .github
- spec
If you don't want to be on this list, please reach out or open a PR.
=> chore: add org approvers

community-members.md, config/open-feature/org.yaml
This PR nominates @kinyoklion and @thomaspoignant to the TC. They have expressed interest in the role and responsibilities outlined in the [TC charter](https://github.com/open-feature/community/blob/main/tech-committee-charter.md#responsibilities-of-the-technical-committee).
@agentgonzo and @InTheCloudDan have decided to step down. Thanks to both of you for your help with the project!
I've added the existing and prospective TC members, and the GC (the GC has veto power as per the charter). I'll be merging this PR tomorrow unless I hear objections.
=> chore: nominate Ryan Lamb and Thomas Poignant to TC

config/open-feature/sdk-javascript/workgroup.yamls-sdk
@lukas-reining has contributed to the spec and related discussions, and implemented multi-client support in the both JS SDKs. Lukas implemented events and init/shutdown in the server-side SDK. He also contributed the config-cat JS provider.
https://github.com/open-feature/js-sdk/pull/429
https://github.com/open-feature/js-sdk/pull/436
https://github.com/open-feature/js-sdk-contrib/commit/495bf690b7d83d429622cfcc554ece2b6fb9a34e
@lukas-reining please approve to show you accept the responsibilities [here](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md#approver) and you'd like to be in the role!
=> chore: add lukas-reining to sdk-js approvers

SECURITY.md
- adds updated security disclosure docs
This is a slight duplication of the security disclosure found in the [docs](https://openfeature.dev/docs/reference/contributing#security-disclosure).
GitHub docs: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability
=> Update vulnerability reporting procedure

CONTRIBUTOR_LADDER.md
Minor updates to contrib ladder. Currently I think CODEOWNERS is emphasized too much. Really it's all done with the community config since the CODEOWNERS uses teams.
=> chore: minor updates to contrib ladder

config/open-feature/org.yaml
Adds some folks who are already mentioned in contrib `component_owners.yaml` files, and alphabetized org members.
=> add members, alphabetize

governance-charter.md
Fixed typo removed "five" from "five seven" in line 34 so it just reads "seven."
=> fix typo in governance-charter.md

.github/ISSUE_TEMPLATE/membership.md
Update line 19 check list item with correct contributor ladder link
I believe this fixes #234 by @agardnerIT
=> fix contributor ladder link in membership.md

SECURITY.md
.github has the policy that is automatically injected into all repos, so I'm redirecting to there.
See also: https://github.com/open-feature/.github/pull/50
fixes: https://github.com/open-feature/.github/issues/49
=> chore: redirect to security to .github

config/open-feature/org.yaml, config/open-feature/sdk-rust/workgroup.yaml
- adds sheepduke to the org
- adds sheepduke as a Rust maintainer
=> add sheepduke to the org and Rust SDK

config/open-feature/cloud-native/workgroup.yaml, config/open-feature/sdk-golang/workgroup.yaml
@bacherfl has contributed significantly to flagd, OFO, but more recently also the go-contribs (he implemented the in-process flagd provider). He's also done work on the go-sdk. @craigpastro helped design and update the fractional evaluation algorithm, added contextual data to flagd evaluations, and also has fixed some flagd bugs
This PR:
* promotes @bacherfl to maintainer in cloud-native team
* adds @bacherfl to maintainer in go-sdk team
* adds @craigpastro to the cloud-native team as an approver
=> chore: promote bacherfl, add craigpastro

config/open-feature/org.yaml
This contributor recently added some tests: https://github.com/open-feature/java-sdk-contrib/pull/468
@DBlanchard88 please comment on this PR and confirm if you're interested in being part of the OpenFeature org. It comes with no obligation, but it will allow us to `@` you and assign you issues.
=> chore: add DBlanchard88 to org

config/open-feature/cloud-native/workgroup.yaml, config/open-feature/org.yaml
Renames the `schemas` repo to `flagd-schemas` as mentioned in slack.
As of yet, this is all flagd-specific stuff. It's the .proto files and json schemas for flagd. I think we risk come confusion by omitting the flagd name here.
This will not impact any submodule pulls, etc, since Github does redirects etc.
=> chore: rename schemas -> flagd-schemas

config/open-feature/org.yaml
@vpetrusevici recently added a Flagsmith .NET provider: https://github.com/open-feature/dotnet-sdk-contrib/pull/89
@vpetrusevici please confirm so we can automatically add you to PRs involving your provider.
=> chore: add vpetrusevici to org

config/open-feature/sdk-java/workgroup.yaml
@liran2000 has added numerous providers in [Java](https://github.com/open-feature/java-sdk-contrib/blob/main/.github/component_owners.yml) and [Go](https://github.com/open-feature/go-sdk-contrib/blob/main/.github/component_owners.yml), contributed to various discussions, and blog posts.
@thisthat is an approver in the [cloud-native](https://github.com/orgs/open-feature/teams/cloud-native-approvers) team, has contributed to the [flagd Java provider](https://github.com/open-feature/java-sdk-contrib/blob/main/.github/component_owners.yml) including significant new features and bug fixes, reviewed and contributed to [numerous](https://github.com/open-feature/java-sdk/commit/bad5b0a7f5167d0b57bf502ce86b32b1c538746c) [Java](https://github.com/open-feature/java-sdk/pull/531) …
=> chore: add liran2000 and thisthat to Java approvers

config/open-feature/org.yaml, config/open-feature/sdk-javascript/workgroup.yaml
I'm proposing the addition of a small react-test app repo that we can use to experiment with `@openfeature/react-sdk` features and possibly eventually use for headless e2e test suites.
This PR adds the above, and also deletes `feature-operator`, which was a very old PoC version of the `open-feature-operator`, which was archived and collecting vulns in Snyk.
=> chore: add react-test-app

config/open-feature/org.yaml, config/open-feature/spec-definition/workgroup.yaml, config/open-feature/spec-evaluation/workgroup.yaml
Team memberships in OpenFeature are configured through this repo.
In this PR, I've added 2 teams: one related to helping define an evaluation wire protocol, and one for helping to develop a standard flag definition.
If you're interested in joining either team, please add your github username in the associated files (as a maintainer). We'll then assume you're interested in helping to develop these standards, by contributing to discussions, doing PoCs, etc.
=> chore: add new spec teams

config/open-feature/cloud-native/workgroup.yaml, config/open-feature/utils/workgroup.yaml
No point in having a group just for this, and it's clearly flagd-related.
=> chore: move flagd-testbed to cloud-native team

community-members.md, config/open-feature/org.yaml, config/open-feature/sdk-javascript/workgroup.yaml
This PR nominates @lukas-reining to the TC. They have expressed interest in the roles and responsibilities outlined in the [TC charter](https://github.com/open-feature/community/blob/main/tech-committee-charter.md?rgh-link-date=2023-05-11T16%3A45%3A22Z#responsibilities-of-the-technical-committee).
- https://github.com/pulls?q=is%3Apr+is%3Amerged+author%3Alukas-reining+archived%3Afalse+sort%3Aupdated-desc+
- @beeme1mr from the GC
- @toddbaert from the TC
=> chore: add Lukas Reining to TC

config/open-feature/org.yaml
@askpt has helped with numerous .NET issues. He:
- removed the Moq lib: ([here](https://github.com/open-feature/dotnet-sdk/commit/311987f0ed803b83f7cc1791ccc91129a3234a11) and [here](https://github.com/open-feature/dotnet-sdk/commit/e9858d9d66ad75ff13f6becc311c50d8dd75caa3))
- added the readme to the nuget package [here](https://github.com/open-feature/dotnet-sdk/pull/164).
- [deprecated the OTel hook](https://github.com/open-feature/dotnet-sdk-contrib/commit/755c54960bccac97f6836ea8371d75bc2f1a02bb), and [implemented the metrics hook.](https://github.com/open-feature/dotnet-sdk-contrib/pull/114)
@askpt please comment-on or :+1: this PR to signal your interest!
=> chore: add askpt to org

README.md
The missing anchor is blocking the docs PR.
https://github.com/open-feature/openfeature.dev/pull/309
=> fixed typos, add community meeting anchor

Elections/2023/Election-Guidelines.md
I think we should be linking to the final list of candidates, rather than a PR?
=> fix link to 2023 election candidates

config/open-feature/org.yaml
@laliconfigcat and @luizbon worked together on the dotnet configcat provider.
@laliconfigcat and @luizbon please react with a :+1: or a comment to this PR to confirm your interest. Being an org member has no obligations, but it allows us to ping you on issues, questions, etc.
=> chore: add laliconfigcat and luizbon to org

config/open-feature/org.yaml
@gruebel has recently started contributing to the Python SDK. I would like to nominate @gruebel as a member org.
Some recent contributions include:
- https://github.com/open-feature/python-sdk/pull/256
- https://github.com/open-feature/python-sdk/pull/255
- https://github.com/open-feature/python-sdk/pull/254
- https://github.com/open-feature/python-sdk/pull/253
@gruebel please comment on or 👍 this PR to signal your interest!
=> chore: Add gruebel as a member

config/open-feature/org.yaml
@austindrenski has made a few recent contributions to .NET ([SDK](https://github.com/open-feature/dotnet-sdk/pull/168) and [contrib](https://github.com/open-feature/dotnet-sdk-contrib/pull/124)).
@austindrenski, please :+1: this PR or comment to signal your interest. Membership carries no responsibilities, but is the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md), and allows us to easily ping you, etc.
=> chore: add austindrenski to org

config/open-feature/org.yaml
Add @Olunusib to the org.
@Olunusib has done some minor fixes in flagd:
- https://github.com/open-feature/flagd/pull/1126
- https://github.com/open-feature/flagd/pull/1127
But more recently has contributed features as well:
- https://github.com/open-feature/flagd/pull/1146
- https://github.com/open-feature/flagd/issues/1150
@Olunusib please :+1: or comment to confirm.
=> chore: add Olunusib to org

CONTRIBUTOR_LADDER.md
In a few discussions with contributors, this has been brought up. I don't think consistently attending meetings is NEEDED. Indeed, we have active TC members who don't attend every meeting, which is not surprising considering our global distribution.
=> chore: loosen meeting requirement

config/open-feature/sdk-dotnet/workgroup.yaml
Both @askpt and @austindrenski have made significant contributions to the .NET SDK and contrib. Both have contributed to issues, discussions, and opened fix and feature PRs.
@askpt : 
- https://github.com/open-feature/dotnet-sdk/issues?q=askpt
- https://github.com/open-feature/dotnet-sdk-contrib/issues?q=askpt
- https://github.com/open-feature/dotnet-sdk/pulls?q=is%3Apr+author%3Aaskpt+is%3Aclosed+
@austindrenski 
- https://github.com/open-feature/dotnet-sdk/issues?q=austindrenski
- https://github.com/open-feature/dotnet-sdk-contrib/issues?q=austindrenski
- https://github.com/open-feature/dotnet-sdk/pulls?q=is%3Apr+author%3Aaustindrenski+is%3Aclosed
I am nominating them both for approver. This means they will be granted binding approval (allowing merge) for the dotnet-sdk and …
=> chore: promote askpt, austindrenski to .NET approver

config/open-feature/sdk-javascript/workgroup.yaml
@luizgribeiro has contributed to issues, discussions, and opened fix and feature PRs.
- https://github.com/open-feature/js-sdk/issues?q=luizgribeiro
- https://github.com/open-feature/js-sdk-contrib/issues?q=luizgribeiro
- https://github.com/open-feature/js-sdk/pulls?q=is%3Apr+author%3Aluizgribeiro
I am nominating them for approver. This means they will be granted binding approval (allowing merge) for the js-sdk and js-sdk-contrib. Maintainer-level approval (at least 1) is still required to enable merge.
@luizgribeiro please respond or :+1: this PR if you're interested in [the role](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md#approver).
=> chore: promote luizgribeiro to JS approver

config/open-feature/org/workgroup.yaml, config/open-feature/sdk-python/workgroup.yaml
@federicobond has been the largest contributor to our python artifacts in recent months, and has also been involved in high-level spec discussions. They have certainly met the requirements of maintainership in my opinion.
https://github.com/open-feature/python-sdk/graphs/contributors
https://github.com/open-feature/python-sdk-contrib/graphs/contributors
I'm nominating them for maintainer in the python repos, and approver in the "org" group (spec/website/etc).
@federicobond please approve this issue to signal your interest!
=> chore: promote federicobond

config/open-feature/org.yaml
@ericpattison [added a provider](https://github.com/open-feature/dotnet-sdk-contrib/pull/129) that uses the underlying Microsoft.FeatureManagement lib.
@ericpattison this comes with no obligation, but allows us to ping you etc, please :+1: this or comment to indicate your interest.
=> chore: add ericpattison to org

config/open-feature/sdk-ruby/workgroup.yaml
@maxveldink has contributed to issues, discussions, and opened fix and feature PRs. He's also pushing for adoption at his company.
- https://github.com/open-feature/ruby-sdk/issues?q=maxveldink
- https://github.com/open-feature/ruby-sdk/pulls/maxveldink
I am nominating them for approver. This means they will be granted binding approval (allowing merge) for the ruby-sdk and ruby-sdk-contrib.
Requires: https://github.com/open-feature/community/pull/334
@maxveldink please respond or :+1: this PR if you're interested in [the role](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md#approver).
=> chore: promote maxveldink

config/open-feature/org/workgroup.yaml
This PR:
- adds `fabriziodemaria` as an org approver
- alphabetized org approvers
@fabriziodemaria has contributed to the spec (especially around client) and helped implement a few SDKs.
@fabriziodemaria please let us know if you're interested!
Note @benjiro and @kinyoklion were duped in this list previously.
=> chore: fabriziodemaria org approver

config/open-feature/sdk-golang/workgroup.yaml
@thisthat is already a Java approver. He contributes regularly to spec discussions, and reviews issues in both Java and Go.
Though his contributions in Go SDK are mostly reviews, considering his skills in that language (proven by his many contributions in flagd and OFO) and his Java contributions, I think he'll be able to contribute significantly to the quality of our Go SDK.
2023: https://github.com/thisthat?tab=overview&from=2023-12-01&to=2023-12-31&org=open-feature
2024: https://github.com/thisthat?tab=overview&from=2024-02-01&to=2024-02-06&org=open-feature
=> chore: add thisthat to approvers

config/open-feature/org/workgroup.yaml
[maxveldink](https://github.com/maxveldink) has contributed to spec discussions, attended meetings, and is doing great working [helping with the Ruby SDK implementation](https://github.com/open-feature/ruby-sdk/commits?author=maxveldink).
This allows him approval on spec/website/etc PRs.
=> chore: add maxveldink to org approvers

config/open-feature/org/workgroup.yaml
@nicklasl has made significant contributions especially to client SDKs:
https://github.com/open-feature/kotlin-sdk/graphs/contributors
https://github.com/open-feature/swift-sdk/graphs/contributors
They've been involved in spec discussions and attend meetings frequently.
This gives @nicklasl approval in spec/website/etc PRs.
@nicklasl please indicate here if you're interested.
=> chore: add nicklasl org approvers

config/open-feature/sdk-javascript/workgroup.yaml
@jonathannorris a feature flagging SME (co-founder and CTO at [DevCycle](https://devcycle.com/)). He's helped in spec development, regularly attends meetings, reviews PRs, and helped build the DevCycle web/server providers (which are build directly into the DevCycle SDKs).
@jonathannorris please :+1: or comment on this PR to confirm!
=> chore: add jonathannorris to JS approvers

README.md
The YouTube link in the Readme was directing to the wrong place
=> Fix YouTube link in Readme

config/open-feature/org.yaml
@ssharaev has [expressed interest](https://github.com/open-feature/java-sdk/pull/848#pullrequestreview-1961936841) in joining the OpenFeature org. Sviatoslav recently [contributed the context propagation feature](https://github.com/open-feature/java-sdk/pull/848) to the Java SDK. 🙇‍♂️
@ssharaev please signal your interest by adding 👍 or approving this PR. After it's merged, you receive an email inviting you.
=> chore: add ssharaev to org

config/open-feature/org.yaml
- enables public access to the ruby sdk contrib repo
Requested on Slack: https://cloud-native.slack.com/archives/C06M49903PV/p1712066177009579
=> chore: make ruby sdk contrib repo public

config/open-feature/org.yaml
@colebaileygit has expressed interest in joining the OpenFeature org. Cole has been busy contributing [custom seeding in the fractional operation in flagd](https://github.com/open-feature/flagd/issues/1264) and an [in-process Python provider](https://github.com/open-feature/python-sdk-contrib/pull/74).
@colebaileygit please signal your interest by adding 👍 or approving this PR. After it's merged, you receive an email inviting you.
=> chore: add colebaileygit to the org

config/open-feature/org.yaml
@jenshenneberg has [expressed interest](https://cloud-native.slack.com/archives/C06EDTWU25B/p1713301351138369?thread_ts=1713211358.968929&cid=C06EDTWU25B) in joining the OpenFeature org. Jens has contributed to the .NET SDK and the Statsig Provider.
https://github.com/open-feature/dotnet-sdk-contrib/pulls?q=is%3Apr+author%3Ajenshenneberg
@jenshenneberg  please signal your interest by adding 👍 or approving this PR. After it's merged, you receive an email inviting you.
=> chore: add jenshenneberg to the org

community-members.md, config/open-feature/org.yaml
- adds Andrew to the org
- adds Andrew as an OpenFeature community manager
Andrew has been an active member of the OpenFeature community and a great advocate for feature flags. He has tons of experience building and engaging with a community. In this role, Andrew can leverage CNCF resources and work more closely with the OpenFeature technical and governance committee.
Here are some examples of his previous involvment:
- https://twitter.com/andrewdmaclean/status/1777360060525826240
- https://cloud-native.slack.com/archives/C0344AANLA1/p1712076267789559
- https://blog.devcycle.com/how-openfeature-was-the-key-to-escaping-feature-flag-vendor-lockin-a-vuejs-story/
@andrewdmaclean, please signal your interest by adding 👍 or approving this PR. After it's merged, you receive an email inviting …
=> add Andrew MacLean as a community manager

config/open-feature/org.yaml
@alxckn has expressed interest in joining the OpenFeature org. Alexandre has contributed to the Ruby SDK and the Ruby contribs repo.
- https://github.com/open-feature/ruby-sdk/pulls?q=author%3Aalxckn+
- https://github.com/open-feature/ruby-sdk-contrib/pulls?q=author%3Aalxckn+
@alxckn please signal your interest by adding 👍 or approving this PR. After it's merged, you receive an email inviting you.
=> chore: add alxckn to the org

config/open-feature/sdk-dotnet/workgroup.yaml
- adds Jens Kjær Hjenneberg as a .NET approver
Jens built the Statsig provider for .NET and has helped with many reviews.
=> chore: add Jens as a .NET approver

config/open-feature/org.yaml
@cpitstick-latai has made numerous suggestions and PRs for OFO: https://github.com/open-feature/open-feature-operator/pulls/cpitstick-latai and is considering running it at their org.
@cpitstick-latai, please thumbs up this PR if you are interested in joining the org. It comes with no obligation, but it's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md). It will allow us to ping you on issues/PRs.
=> chore: add cpitstick-latai to org

config/open-feature/org.yaml
@alexandraoberaigner added a mvnw script to the Java contribs: https://github.com/open-feature/java-sdk-contrib/pull/811
@alexandraoberaigner, please thumbs up this PR if you are interested in joining the org. It comes with no obligation, but it's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md). It will allow us to ping you on issues/PRs.
=> chore: add alexandraoberaigner to org

config/open-feature/org.yaml
@anghelflorinm is from Google and is interested in helping to [define a flag manifest and codegen solution](https://github.com/orgs/open-feature/discussions/383) for OpenFeature.
Florin has created the #openfeature-codegen Slack channel and has started a [project proposal](https://docs.google.com/document/d/19CTHDUZ6J-GLuDGxO_dmycieG99telHV0SX7cJcGAsw/edit?usp=sharing).
@anghelflorinm, please thumbs up this PR if you are interested in joining the org.
=> chore: add anghelflorinm to org

config/open-feature/org.yaml
@ejscunha has [graciously donated an Elixir SDK](https://cloud-native.slack.com/archives/C0344AANLA1/p1722364342242609) to OpenFeature.
@ejscunha, please thumbs up this PR if you are interested in joining the org.
=> add Eduardo to the org

config/open-feature/org.yaml
@adams85 is from ConfigCat and reviewed the `config-cat` and `config-cat-web` providers and showed interest to help maintain those as official providers. (https://github.com/open-feature/js-sdk-contrib/pull/1033)
@adams85 please thumbs up this PR if you want to join the org.
This way we can tag you and assign you to issues. There are no other obligations from joining.
=> chore: add adams85 to org

config/open-feature/org.yaml
@djosephsen has been helping with flagd features, specifically https://github.com/open-feature/flagd/issues/1344
@djosephsen please approve or :+1: this PR if you are interested. There's no obligation in joining but it means we'll be able to ping you and you will no longer need approvals to run CI jobs.
=> chore: add djosephsen to org

config/open-feature/org.yaml
@ryanprayogo has recently found / fixed a couple [java](https://github.com/open-feature/java-sdk/pull/1057) [bugs](https://github.com/open-feature/java-sdk/pull/1060)!
Thanks @ryanprayogo! This adds you to the OpenFeature org. It comes with no obligation, but allows us to assign/ping you, and it's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
@ryanprayogo Please approve or :+1: this PR to signal you're interested.
=> chore: invite ryanprayogo

config/open-feature/org.yaml
@UtkarshSharma2612 recently made a significant enhancement to the flagd-java provider: https://github.com/open-feature/java-sdk-contrib/pull/925
This adds them to the org. 
@UtkarshSharma2612 please :+1:  or approve this PR to signal your interest; there's no obligation but it allows us to ping/add/assign you and it's the first step on the contributor ladder.
=> chore: add UtkarshSharma2612 to org

config/open-feature/org.yaml
@pradeepbbl has been working on some enhancements to flagd providers to support custom name resolvers: https://github.com/open-feature/flagd/pull/1414 
@pradeepbbl when this is merged, it will add you to the org. Being in the org comes with no obligation but allows us to assign you and ping you easier, etc. Please :+1: or approve this PR if you want to join and you will get an email invite.
=> chore: add pradeepbbl

config/open-feature/org.yaml
@guidobrei actively contributed to the [java-sdk](https://github.com/open-feature/java-sdk/pulls/guidobrei) and the [java-sdk-contrib](https://github.com/open-feature/java-sdk-contrib/pulls/guidobrei) also helped in[ reviews for multiple prs](https://github.com/search?q=org%3Aopen-feature+guidobrei&type=pullrequests). Hence, I want to propose adding him as a community member.
@guidobrei, please thumbs up this PR if you're interested in joining the organization. There's no obligation to join.
=> chore: add guidobrei to org

config/open-feature/sdk-java/workgroup.yaml
@aepfli has made significant contributions to the OpenFeature Java ecosystem. They have:
- conceived and built our Junit testing extension, allowing simple and consistent testing via annotations: https://github.com/open-feature/java-sdk-contrib/tree/main/tools/junit-openfeature
- have made [numerous](https://github.com/open-feature/java-sdk-contrib/pull/942) [contributions](https://github.com/open-feature/java-sdk-contrib/pull/860) to the [SDK](https://github.com/open-feature/java-sdk/pull/1095) and [flagd](https://github.com/open-feature/java-sdk-contrib/pull/833) provider
- they've been active contributors to the community, representing OpenFeature at conferences and in fact building our community management automation in use in this PR
Full disclosure, @aepfli is a member of my …
=> chore: promote aepfli to java maintainer

README.md
- switch the LFX Zoom account
- updates link to the LFX public calendar
This is the initial PR to switch to a Zoom account owned by the Linux Foundation.
=> chore: switch to LFX Zoom account

config/open-feature/org.yaml
@alemrtv recently added [significant functionality](https://github.com/open-feature/flagd/pull/1448) to flagd (a new command line argument to add arbitrary static context values to all evaluations)
@alemrtv this PR adds you to the OpenFeature org. Being an org member comes with no obligation at all, but it allows you to run actions on PRs and makes it easier for us to ping you. It's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
If you approve or :+1: this PR, we will merge it and you will receive an org invite in your email.
=> chore: add alemrtv

config/open-feature/org.yaml
@arttonoyan has added the DI features to the dotnet SDK:
- https://github.com/open-feature/dotnet-sdk/pull/310
- https://github.com/open-feature/dotnet-sdk/pull/324
@arttonoyan this adds you to the org. This comes with no obligation but allows us to ping you and add you to PRs easier and is the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
If you're interested, please :+1: or approve this PR and when merged you will get an invite to the org in your email.
=> chore: add arttonoyan

config/open-feature/org.yaml
@cupofcat has been working on flagd and flagd providers:
- https://github.com/open-feature/go-sdk-contrib/pull/598
- https://github.com/open-feature/flagd/issues/1481
- https://github.com/open-feature/flagd/issues/1487
@cupofcat this PR adds you to the OpenFeature org. If you approve or :+1: , we will merge it and you will get an invite. Being in the org comes with no obligation but allows us to contact you more easily and it's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
=> chore: add cupofcat

config/open-feature/sdk-dotnet/workgroup.yaml
* Removed `askpt` from the `approvers` list.
* Added `askpt` to the `maintainers` list.
I have been actively maintaining the dotnet-sdk for the last couple of months.
=> chore: add askpt as a .NET maintainer

config/open-feature/sdk-java/workgroup.yaml
@chrfwow has been contributing significantly to our Java implementations:
- finally hook change in SDK: https://github.com/open-feature/java-sdk/pull/1262
- flag metadata support in the flagd java provider: https://github.com/open-feature/java-sdk-contrib/pull/1122
And most recently identified a deadlock in the Java SDK, opened an issue describing it, and has been helping to guide the fix by a new contributor: https://github.com/open-feature/java-sdk/pull/1314
I'm nominating them for Java approver. @chrfwow please approve or :+1: this PR for signal your interest. For transparency, @chrfwow works at my company. I will require at least one green approval from a contributor from elsewhere.
=> chore: add chrfwow to Java approvers

config/open-feature/org.yaml
@leohoare add support for async evaluation in the Python SDK.
- https://github.com/open-feature/python-sdk/pull/413
@leohoare this PR adds you to the OpenFeature org. If you approve or 👍 , we will merge it and you will get an invite. Being in the org comes with no obligation but allows us to contact you more easily and it's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
=> chore: add leohoare to org

config/open-feature/org.yaml
@sideshowcoder recently fixed some concurrency issues in the Java SDK: https://github.com/open-feature/java-sdk/pull/1314
Hey @sideshowcoder! This PR invites you to join the OpenFeature org. Joining the org comes with no obligation, but allows us to ping you, and allows CI to run automatically on PRs from your forks. It's the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
Please approve or :+1: this PR to signal your interest, and you'll receive an invite email.
=> chore: add sideshowcoder

config/open-feature/org.yaml
Removing members that failed to accept to invite. This will prevent the bot from repeatedly spamming them every few weeks.
https://github.com/orgs/open-feature/people/pending_invitations
> I left cupofcat since his invite is new and jrydberg since he's on the GC.
=> chore: remove members who didn't accept the invite

config/open-feature/org.yaml
@kriscoleman has been contributing to the OpenFeature CLI:
https://github.com/open-feature/cli/issues?q=is%3Apr%20is%3Aopen%20author%3Akriscoleman
@kriscoleman when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation but it's the first step on the https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md. Please approve or 👍 this PR to signal your interest!
=> chore: add Kris Coleman to the org

config/open-feature/org.yaml
@gdegiorgio added an AWS SSM provider, and also fixed our package generation in js-contribs
https://github.com/open-feature/js-sdk-contrib/pull/1221
@gdegiorgio - this PR will add you to the org, which is the first step on the contributor ladder. Please approve or :+1: to signal your interest and you will get an email invite.
=> chore: add gdegiorgio

ADOPTERS.md, interested-parties.md
Adds Adeo as an interested party
- adds [Adeo](https://github.com/adeo) as an interested party and adopter
I'm adding to this list due to my involvement in the promotion and adoption of OpenFeature in the Adeo organization.
I'm currently leading internal interest groups within Adeo, and we are aiming for the adoption of OpenFeature as a standard. I also have been involved in local community talks to bring awareness to the benefits of OpenFeature (and feature toggling in general) as a practice to allow trunk-based development and continuous delivery.
=> Add Adeo organization as interested-party and adopter

config/open-feature/org.yaml
[Watchman](https://github.com/open-feature/watchman) was a prototype created for a previous KubeCon
=> achieve inactive repo watchman

config/open-feature/org.yaml
@kylejuliandev has been contributing to the OpenFeature dotnet SDK and contrib:
- https://github.com/search?q=is%3Apr%20author%3Akylejuliandev%20org%3Aopen-feature%20&type=pullrequests
He also created a blog post:
- https://blog.kylejulian.dev/posts/open-feature-intro/
@kylejuliandev, when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation, but it's the first step on the https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md. Please approve or 👍 this PR to signal your interest!
=> chore: Add kylejuliandev to organization members list

config/open-feature/org.yaml
@falghi added a Flipt provider for Ruby.
https://github.com/open-feature/ruby-sdk-contrib/pull/51
@falghi  - this PR will add you to the org, which is the first step on the contributor ladder. Please approve or 👍 to signal your interest and you will get an email invite.
=> chore: Add falghi to organization members list

config/open-feature/org.yaml
@jblacker recently contributed the multi-provider to the Go ecosystem based on @bbland1 initial implementation.
https://github.com/open-feature/go-sdk-contrib/pull/669
@jblacker, when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation, but it's the first step on the [main/CONTRIBUTOR_LADDER.md](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md). Please approve or 👍 this PR to signal your interest!
=> Add jblacker to the org

config/open-feature/org.yaml
@erka has extensive feature flagging and Go experience. He has contributed to OFREP, the spec, and the Go SDK.
- Issues: https://github.com/search?q=org%3Aopen-feature+author%3Aerka&type=issues
- prs: https://github.com/search?q=org%3Aopen-feature+author%3Aerka&type=pullrequests
@erka, when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation, but it's the first step on the [main/CONTRIBUTOR_LADDER.md](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md). Please approve or 👍 this PR to signal your interest!
=> Add erka to the org

config/open-feature/sdk-swift/workgroup.yaml
Adding https://github.com/open-feature/ofrep-swift-client-provider/ to the list of the repositories managed by the swift maintainer group.
=> feat: Adding ofrep swift repo in the list for swift maintainers

config/open-feature/org.yaml
The governance board has changed, and we adapted the org owners, but not the team members.
=> chore: update governanve board to reflect current members

config/open-feature/sdk-java/workgroup.yaml
Chrfwow has had a great impact on the Java SDK. His insights into concurrency and his level of detail help us thrive and move forward. His feedback on pull requests and issues (not only in the Java realm) has been highly valuable all the time. Hence I propose to promote him to maintainer of the Java realm.
- https://github.com/open-feature/java-sdk/pulls?q=is%3Apr+author%3Achrfwow
- https://github.com/open-feature/java-sdk-contrib/pulls?q=is%3Apr+author%3Achrfwow
- overall: https://github.com/search?q=org%3Aopen-feature+involves%3Achrfwow&type=issues
Full Disclosure: @chrfwow is working with me at Dynatrace, so I would love to hear feedback and insights from others regarding this promotion.
@chrfwow, if you approve of this promotion, please approve this pull request.
=> promote chrfwow to java maintainer

CONTRIBUTOR_LADDER.md
At the prompt of some contributors and maintainers, I've revisited the contributor ladder to attempt to make the responsibilities of each role more concise and consistent. The changes aren't substantial; the main improvement is to provide something slightly closer to a checklist so maintainers can be confident they are covering all the basic responsibilities day-to-day.
Let me know if you think there's anything missing here, or if a different format would be helpful, etc.
=> chore: update contributor ladder with more concise responsibilities
