open-feature/community

interested-parties.md

Add @oleg-nenashev to interested parties, add columns for Gitlab username and affiliations

---

interested-parties.md

This PR adds Kevin Chu as a interested party

Add kbychu to interested parties

---

MAINTAINERS.md

Create the Maintainers file

---

interested-parties.md

FYI @AloisReitbauer, as we briefly discussed today

Add @AloisReitbauer to the list of interested parties

---

interested-parties.md

Update @oleg-nenashev's affiliations, add Gitlab profile

---

interested-parties.md

Add Michael Friedrich, GitLab to interested parties

---

interested-parties.md

👋🏽 @oleg-nenashev!
Signed-off-by: Stephen Augustus <foo@auggie.dev>

interested-parties: Add Stephen Augustus (Cisco)

---

interested-parties.md

Order interested parties

---

README.md

Migrate the repository to the new domain

---

interested-parties.md

Add contact information for myself and LaunchDarkly

Adding LaunchDarkly

---

governance-charter.md

Add governing board and TSC members

---

interested-parties.md

https://posthog.com/docs/user-guides/feature-flags

add posthog

---

mission-vision.md

Updated the mission statement from "...standardizing feature flagging for developers" to "...standardizing feature flagging for everyone". Everyone is more inclusive but more vague. However, I believe that standardizing various aspects of feature flagging will benefit more than just developers. For example, a DevOps engineer could build tooling around the OpenFeature standard to automate feature testing in their pipeline.

Update mission statement to be inclusive

---

.github/CODEOWNERS

Add @beeme1mr to codeowners

---

branding-guidelines.md

Add initial branding guidelines

---

interested-parties.md

As well as Vic Vuci (myself) from DevCycle as an interested individual (also affiliated with Taplytics)

Add DevCycle to Interested Parties

---

governance-charter.md

Update community meeting link

---

README.md

Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>

update governance section with sandbox information

---

governance-charter.md

Signed-off-by: Steve Arch <sarch@cloudbees.com>

chore: Added links to member profiles

---

README.md

Signed-off-by: Justin Abrahms <jabrahms@ebay.com>

Add an adopters section.

---

governance-charter.md

fixed stale docs about committee vacancies

---

MAINTAINERS.md

allows me to better help with incubation efforts and requests to the CNCF (snyk support and other perks of being a cncf project)

Add DavidPHirsch to maintainers

---

governance-charter.md

Remove kbychu from governance committee

---

.github/CODEOWNERS

As discussed with @AloisReitbauer

Remove @oleg-nenashev from CODEOWNERS

---

interested-parties.md

Adds me to the list of interested individuals
Signed-off-by: Weyert de Boer <weyert@gmail.com>
Added myself to the interested parties document
None
None

update interested parties

---

areas-of-interest.md

Signed-off-by: David Hirsch david.hirsch@dynatrace.com
- add areas of interest for TOC and governance
https://github.com/open-feature/community/issues/111 
###Follow up tasks
add areas of interest

Create areas of interest page

---

governance-charter.md

adding overview and goals sections

Adding Overview and Goals

---

ADOPTERS.md

Create adopter list

---

README.md

Signed-off-by: David Hirsch <David.hirsch@dynatrace.com>
fixed adopters link

added link to adopters

---

CONTRIBUTOR_LADDER.md

Draft of a contributor ladder, details still missing

Create contributor ladder

---

renovate.json

Disable Renovate dashboard to avoid Renovate re-opening it every time:
https://github.com/open-feature/community/issues/125#event-8151511404
Fixes #125

chore: Disable Renovate dashboard

---

governance-charter.md

Signed-off-by: David Hirsch <79513080+DavidPHirsch@users.noreply.github.com>
consolidation and corrections

Update governance charter

---

SECURITY.md

Update security Policy

---

.github/ISSUE_TEMPLATE/adopter----add-company-name-.md

Creation of adopter issue

---

ADOPTERS.md

add dynatrace to adopters

---

tools/peribolosbuilder.go

Added check for handling only directories within the config folder, so we are ignoring the readme.md in the build.

fix: handling of readme in config folder

---

config/open-feature/org.yaml

Signed-off-by: Simon Schrottner <simon.schrottner@dynatrace.com>

fix: adding missing users

---

config/README.md
config/open-feature/cloud-native/workgroup.yaml
config/open-feature/education/workgroup.yaml
config/open-feature/org.yaml
config/open-feature/org/workgroup.yaml
config/open-feature/sdk-dotnet/workgroup.yaml
config/open-feature/sdk-golang/workgroup.yaml
config/open-feature/sdk-java/workgroup.yaml
config/open-feature/sdk-javascript/workgroup.yaml
config/open-feature/sdk-python/workgroup.yaml
config/open-feature/utils/workgroup.yaml

update user permission based on contributions

---

config/open-feature/org.yaml

Membership request 'aepfli' #177

---

config/open-feature/org.yaml
config/open-feature/org/workgroup.yaml
config/open-feature/tooling/workgroup.yaml

As we want to extract our tooling into an own repository, we need to create a new one :)
relates: #180

feat: add repo for community tooling

---

tools/peribolosbuilder.go

As triage is not enough for approvers, we increase them to write.

fix: increase approver permissions to write

---

config/open-feature/cloud-native/workgroup.yaml

- removes @thschue from cloudnative-approvers

chore: remove @thschue from cloudnative-approvers

---

config/open-feature/org.yaml

- adds @staceypotter as Org Member
- closes #188 
#188

Add staceypotter as Org Member

---

config/open-feature/education/workgroup.yaml
config/open-feature/org.yaml

- add a tutorial repo
The repo is marked as private until the tutorials are ready for users.

chore: add tutorial repo

---

config/open-feature/org.yaml

See title.
Robert attended our Python SDK meeting last week and will be helping with our 1.0 efforts.

Add ARobertsCollibra to org

---

interested-parties.md

updates links for our mailing list & contributor guides/docs

updated outdated links

---

config/open-feature/org.yaml

add sindhuinti org mem

---

interested-parties.md

- Add myself to interested parties

docs: add agardnerit to interested parties

---

README.md

Adds the OpenFeature YouTube Channel to the Socials section.

Add YouTube Channel to Socials section in README.md

---

config/open-feature/org.yaml

Add org members

---

config/open-feature/org.yaml

federicobond has been helping in the Python SDK
@federicobond **this is totally optional, and comes with no obligations.** It will allow us to ping you on PRs, issues, etc.
If you're not interested, please let me know and I will close this PR.

chore: add federicobond to org

---

config/open-feature/sdk-python/workgroup.yaml

@federicobond has contributed significant improvements to the Python SDK.
I've nominated them for approver, and they've expressed interest in the [responsibilities](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md).
@federicobond please approve this PR if you agree!

chore: add federicobond to approvers

---

config/open-feature/cloud-native/workgroup.yaml

This PR adds @bacherfl and @odubajDT to cloud-native [approvers](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md#approver). @bacherfl and @odubajDT please approve this PR to express interest in taking on this role.
@bacherfl:
- remediated [CVE-2023-29018](https://github.com/open-feature/open-feature-operator/security/advisories/GHSA-cwf6-xj49-wp83), and made [permissions improvements](https://github.com/open-feature/open-feature-operator/commit/6f1f93c98c7b8fbee534cc7db63fc396fa5b73c7) to OFO
- implemented [sem-ver](https://github.com/open-feature/flagd/pull/675) and [other](https://github.com/open-feature/flagd/pull/658) custom evaluators in flagd
- has done various [refactors](https://github.com/open-feature/flagd/commit/01016c7df7c5f653cdadf151539432f692f36251) …

chore: update cloud-native approvers

---

config/open-feature/org.yaml
config/open-feature/org/workgroup.yaml

Adds TOC proposal fork to org group

chore: add TOC proposal and group

---

config/open-feature/org.yaml
config/open-feature/sdk-kotlin/workgroup.yaml
config/open-feature/sdk-swift/workgroup.yaml

- adds kotlin-sdk to org management
- add swift-sdk to org management
- adds contributors from spotify
Marked as draft until we have the right people identified.
@fabriziodemaria @Calibretto @vahidlazio @nickybondarenko please add recommend maintainers and approvers. Keep in mind they will need to already be org members. Let me know if there's anyone else to invite, and keep in mind our charters and code of conduct, https://github.com/open-feature/community/blob/main/README.md.
I will keep myself as a maintainer for the time being to help get things setup, like CI, etc. Long term I may not continue in the role since (at least for now) I'm not too familiar with iOS or Android development.

chore: add kotlin/swift repos to mgmt

---

config/open-feature/sdk-swift/workgroup.yaml

- Adds additional maintainers of the Swift repository

chore: add swift maintainers

---

config/open-feature/org.yaml

@Billlynch has been working on some related JS stuff, and helping with the client spec.
Please comment here if you'd like to join or not. Once this is merged you'll get an invite.

chore: invite Billlynch

---

config/open-feature/org.yaml

@craigpastro has made numerous contributions to flagd.
@craigpastro please respond indicating if you'd like to join the org (which will allow us to ping you on PRs and is the first step on the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md)). 
Your efforts are appreciated whether or not you decide to join!

chore: add craigpastro to org

---

config/open-feature/utils/workgroup.yaml

Missed this on: https://github.com/open-feature/community/pull/250

chore: update test-harness ref

---

CONTRIBUTOR_LADDER.md

broken links to the community configuration

Fixing broken links

---

interested-parties.md

- Adds me and my company as interested parties

add fernandobandeira and alternativepayments interested parties

---

README.md

Fleshed out the meeting section a bit, added our cncf chapter page as well.

Update meetings info in README.md

---

config/open-feature/org.yaml

@dgorton opening this in favor of https://github.com/open-feature/community/pull/270

chore: add dgorton

---

Elections/2023/Candidates.md

Adding myself as a candidate for the Governance Committee

Update Candidates.md with Jonathan Norris

---

Elections/2023/Candidates.md

- adds this new feature
Fixes #1234523

update: Added Alex for 2024

---

Elections/2023/Candidates.md

Add myself as candidate for the election
N/A

update: Added Weyert candidacy for 2024

---

Elections/2023/Candidates.md

Nominating myself to continue serving on the OpenFeature Governance Board

nominate myself to continue on GC

---

Elections/2023/Candidates.md

Add myself as candidate for the Governance Committee election. 
n/a 
n/a
n/a
n/a

Add oxddr@ to list of candidates for OpenFeature Governance Commitee.

---

Elections/2023/Candidates.md

Add kamil-nowosad@ to the list of candidates for the Governance Commitee

Add kamil-nowosad@ to the list of candidates for the Governance Commitee

---

Elections/2023/Candidates.md

- adds this new feature
Fixes #1234523

add myself to election

---

Elections/2023/Candidates.md

moves Johan Rydberg to keep the list sorted alphabetically

Update Candidates.md alphabetical sort

---

config/open-feature/org.yaml
config/open-feature/spec-evaluation/workgroup.yaml

- adding repo for protocol
- adding team ownership

chore: add protocol repo

---

config/open-feature/org.yaml

Adds nikolasleblanc to list of org members
- Adds @nikolasleblanc to the list of org members

Add nikolasleblanc to org

---

config/open-feature/org.yaml

Add Luiz to Org.
He contributed to JS SDK and wants to also help on the Nest.js SDK.

chore: add luizgribeiro to org

---

README.md

Updates our calendar & community meetings section

Update calendar & community meetings in README.md

---

ADOPTERSandVENDORS.md

updating to include also vendors.
Final goal is to have a banner on the home page

Update and rename ADOPTERS.md to ADOPTERSandVENDORS.md

---

Elections/2023/Election-Guidelines.md

updates the candidates.md link (it was broken) in Election-Guidelines.md

Update candidates.md link in Election-Guidelines.md

---

ADOPTERS.md
VENDORS.md

- split vendors and adopters files

split vendors and adopts

---

Elections/2023/Election-Guidelines.md

Updates the election guidelines with the *new* helios voting link.

Update helios link in Election-Guidelines.md

---

config/open-feature/spec-evaluation/workgroup.yaml

@lukas-reining (OpenFeature TC member) has started to contribute more to the protocol by proposing some changes and helping with the openAPI spec.
@lukas-reining please 👍 or comment on this PR to confirm!

Add Lukas as protocol maintainer

---

interested-parties.md

Add AWS as an interested party.

Add AWS AppConfig to interested-parties.md

---

interested-parties.md

Updates the name of my employer after we got acquired.
N/A

Update the name of my employer

---

config/open-feature/sdk-python/workgroup.yaml

- adds @gruebel as a Python approver
Has contributed to the Python SDK and provided valuable feedback during PR reviews.

chore: add gruebel as a python approver

---

config/open-feature/org.yaml

@juanparadox has been experimenting with OpenFeature x Next.js! :raised_hands: 
@juanparadox please signal your interest by adding :+1: or approving this PR. After it's merged, you receive an email inviting you.

chore: add juanparadox to org

---

config/open-feature/org.yaml

- add ajwotto to list of org members

add ajwootto to members in org.yaml

---

config/open-feature/org.yaml

- adds jarebudev to the list of members in org.yaml

added jarebudev to members in org.yaml

---

branding-guidelines.md
docusaurus-sidebar.js
presentations.md

- adds a page that lists presentations
This is just a list of presentations I could find quickly. Please let me know what I've missed and I would be happy to add them.
We should also create a shareable PowerPoint template that can be shared.

feat: add presentations page

---

interested-parties.md

Add VWO as an interested organization
- adds this new feature
Fixes #1234523

Add VWO as an interested organization

---

config/open-feature/org.yaml

@hairyhenderson has contributed to the go-sdk.
@hairyhenderson please approve or :+1: this PR to signify your interest in org membership.

chore: add hairyhenderson

---

ADOPTERS.md

Replaces Tapico for FNZ on the adopters list
None
Company got acquired
None
None

docs: add FNZ to the adopters list

---

config/open-feature/org.yaml

@tjosepo recently made [some improvements](https://github.com/open-feature/js-sdk/pull/921) to the suspense functionality in the react SDK.
@tjosepo please approve this PR or add a :+1:. Once this is mergef you'll receive an invite email.

chore: add tjosepo to org

---

presentations.md

- Fixes the link to 'Branding Guidelines' page

Fix the link to 'Branding Guidelines' page

---

config/open-feature/org.yaml

chore: add codegen repo

---

config/open-feature/org.yaml

@z4kn4fein is from ConfigCat and showed interest to help maintain the Go `ConfigCat provider` as official provider. (https://github.com/open-feature/go-sdk-contrib/pull/548)
@z4kn4fein please thumbs up this PR if you want to join the org.
This way we can tag you and assign you to issues. There are no other obligations from joining.

chore: add z4kn4fein to org

---

config/open-feature/org.yaml

@wichopy recently contributed a [context mutation hook](https://github.com/open-feature/js-sdk/pull/1031) in the React SDK and has [expressed interest in joining the org](https://github.com/open-feature/js-sdk/issues/1033#issuecomment-2420145102).

chore: add wichopy to org

---

config/open-feature/education/workgroup.yaml

- added openfeature.dev to group
- added @andrewdmaclean as an approver

chore: add andrew as education approver

---

ADOPTERS.md

- Records Minder (https://github.com/mindersec/minder as an adopter of OpenFeature.

Add Minder as an adopter

---

config/open-feature/org.yaml

Jeremy @ABC2015 has offered to work on a Dart Server SDK server.
@ABC2015, please thumbs up this PR if you are interested in joining the org. There's no obligation associated with joining.

chore: add ABC2015 to org

---

config/open-feature/org.yaml

Adds myself (@chrfwow) as member.
I already [contributed](https://github.com/open-feature/java-sdk/pull/1096) to the java sdk and I am currently working on a [contribution](https://github.com/open-feature/dotnet-sdk/pull/323) to the dotnet sdk.

chore: add chrfwow as member

---

config/open-feature/org.yaml

- added missing repositories to config
- ordered repositories alphabetically

feat: update repo list

---

config/open-feature/cloud-native/workgroup.yaml

Adds Lukas as a cloud native maintainer.
- https://github.com/open-feature/open-feature-operator/pull/725

chore: add Lukas as a cloud native maintainer

---

.github/ISSUE_TEMPLATE/publish-item-to-blog--social-media-channels-or-newsletter.md
README.md

- adds BlueSky to Social Media lists

feat: add BlueSky to Social Media lists

---

Elections/2025/Candidates.md
Elections/2025/Election-Guidelines.md

- Get the 2025 content into the repo
https://github.com/open-feature/community/issues/417

2025 election setup

---

config/open-feature/sdk-python/workgroup.yaml

I'd like to promote @gruebel to have maintainer status in Python. He experience has been invaluable. Thanks!
- https://github.com/open-feature/python-sdk/pulls?q=is%3Apr+author%3Agruebel+is%3Aclosed
- https://github.com/open-feature/python-sdk-contrib/pulls?q=is%3Apr+author%3Agruebel+is%3Aclosed

promote grubel to a Python maintainer

---

config/open-feature/org.yaml

@bbland1 has contributed 2 recent changes to the Go SDK:
- https://github.com/open-feature/go-sdk/pull/325
- https://github.com/open-feature/go-sdk/pull/328
@bbland1 when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation but it's the first step on the https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md. Please approve or :+1: this PR to signal your interest!

chore: add bbland1 to org

---

config/open-feature/sdk-dotnet/workgroup.yaml

This pull request updates the list of approvers in the `config/open-feature/sdk-dotnet/workgroup.yaml` file by adding a new member.
* **Approvers list update**:
* Added `kylejuliandev` to the `approvers` section.
@kylejuliandev is actively working on "approving" the PRS from `dotnet` and `dotnet-contrib`. I would like to nominate him as an approver based on his contributions.
@kylejuliandev, please approve this PR or +1 if you accept this nomination!

Promote kylejuliandev to dotnet approver

---

config/open-feature/org.yaml

@WeihanLi has been contributing to the OpenFeature dotnet repository:
https://github.com/search?q=author%3AWeihanLi+org%3Aopen-feature+&type=pullrequests
@WeihanLi, when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation, but it's the first step on the https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md. Please approve or 👍 this PR to signal your interest!

Add WeihanLi to organization members list

---

config/open-feature/org.yaml

@Kielek has been contributing to the OpenFeature Contrib repository:
https://github.com/search?q=author%3Akielek+org%3Aopen-feature+&type=pullrequests
@Kielek, when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation, but it's the first step on the https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md. Please approve or 👍 this PR to signal your interest!

Add Kielek to organization members list

---

interested-parties.md

- adds @vitorvasc as OpenFeature interested party

chore: add vitorvasc as interested party

---

config/open-feature/sdk-dotnet/workgroup.yaml

This pull request updates the list of approvers in the `config/open-feature/sdk-dotnet/workgroup.yaml` file to include a new member.
* [`config/open-feature/sdk-dotnet/workgroup.yaml`](diffhunk://#diff-21c39224351cc866021a644c90f714e7ce4ebd14f8b48fac46f8b068e5ceb978R6): Added `arttonoyan` to the list of approvers.
@arttonoyan actively contributes to the dotnet-sdk by reviewing PRs and helping with his expertise. He was the initial contributor to the DI library, and it is a game-changer for the open-feature/dotnet-sdk.
@arttonoyan, please approve this PR or +1 if you accept this nomination!

Promote arttonoyan to dotnet-approver

---

config/open-feature/org.yaml
config/open-feature/sdk-kotlin/workgroup.yaml

Add Kotlin contrib repo

---

config/open-feature/sdk-golang/workgroup.yaml

@sahidvelji actively contributes to the golang-sdk by reviewing PRs and actively contributing.
- author: https://github.com/search?q=org%3Aopen-feature+author%3Asahidvelji&type=issues
- comments: https://github.com/search?q=org%3Aopen-feature+commenter%3Asahidvelji&type=issues
Based on his contributions, I propose to increase his possible influence by promoting him to approver based on our contribution ladder. https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md
@sahidvelji, please approve this PR or +1 if you accept this nomination!

Promote sahidvelji to golang-approver

---

config/open-feature/sdk-golang/workgroup.yaml

@sahidvelji has been a substantial driver of the go-sdk in recent months. He's contributed significantly to the improvement of the SDK and the OpenFeature CLI, and has been driving the discussion of a possible v2 of the SDK. He's attended multiple community meetings and shown an ability to incorporate community feedback and drive consensus while applying his Go-expertise and advocating adoption at his org.
https://github.com/search?type=pullrequests&q=author%3Asahidvelji+org%3Aopen-feature+
https://github.com/search?type=issues&q=author%3Asahidvelji+org%3Aopen-feature+ 
@sahidvelji please 👍 or approve this PR to signal your interest, after reviewing the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md#maintainer).

chore: promote sahidvelji

---

config/open-feature/org.yaml

@leakonvalinka is actively contributing to flagd for multiple topics. 
- Issues: https://github.com/search?q=org%3Aopen-feature++involves%3Aleakonvalinka&type=issues
- prs: https://github.com/search?q=org%3Aopen-feature++involves%3Aleakonvalinka&type=pullrequests
@leakonvalinka, when merged, this PR will add you to the org (and send you an email invite). It comes with no obligation, but it's the first step on the [main/CONTRIBUTOR_LADDER.md](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md). Please approve or 👍 this PR to signal your interest!

chore: add leakonvalinka to the org

---

config/open-feature/org.yaml

@andreyturkov has been help with flagd and go in general.

chore: add andreyturkov to org

---

config/open-feature/org.yaml
config/open-feature/sdk-cpp/workgroup.yaml

- adds @NeaguGeorgiana23 to the OpenFeature org
- adds a new private C++ repo
@NeaguGeorgiana23 from Google has offered to start working on a C++ SDK. We would like to keep the repo private until the initial structure is in place.

chore: add Georgiana to org, add cpp repo

---

config/open-feature/mcp/workgroup.yaml
config/open-feature/org.yaml

- adds MCP repo, with jonathannorris as maintainer

chore: add MCP repo, with jonathannorris as maintainer

---

config/open-feature/spec-evaluation/workgroup.yaml

Add oxddr (myself) to emeritus and remove from maintainers as I am unable to actively contribute to OFREP project.

Add oxddr to emeritus and remove from maintainers
